name: strokee

description: Application for personal time management

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.17.0         
  table_calendar: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/icons/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
        - asset:  assets/fonts/RobotoCondensed-Light.ttf
        - asset:  assets/fonts/RobotoCondensed-Regular.ttf


